version: "3.8"

services:
  chrome:
    image: selenium/standalone-chrome
    hostname: chrome
    privileged: true
    shm_size: 2g

  web:
    restart: always
    build: .
    env_file:
      - .env
    command: >
      sh -c "python tweet.py"
    depends_on:
      - chrome
